Feat/date picker organism
W170/talenta.magneto365.ui pull request #166
Opened 2024-06-13 18:24 UTC by JuanBallen09

# Description

New organism created called Date Picker organism that combines both components, Date Picker & Mobile Date Picker using the useMediaQuery hook.

## Type of change
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- [X] Test A
- [ ] Test B

**Test Configuration**:

- SDK: Jest
- Software version: 26
- Toolchain: super-test

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-13 20:03 UTC, JMonsalveTL requested changes

2024-06-13 20:03 UTC, JMonsalveTL commented on src/components/UI/organism/DatePicker/DatePicker.component.tsx
You have two components with the same name "DatePicker", although they are different parts it can be confusing, I suggest you change this name, maybe "DatePickerReponsive".

2024-06-13 22:40 UTC, JuanBallen09 commented on src/components/UI/organism/MobileDatePicker/MobileDatePicker.stories.tsx
That dependecy was never install or configured in the library, is was a suggestion that my IDE made without knowing it would cause an error.

2024-06-14 12:11 UTC, JMonsalveTL approved these changes
LGTM

2024-06-14 12:11 UTC, merged